In [2]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
#creating -from list
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2=np.array([1,2,3,4,5,"megha"])
print(arr2,type(arr2),arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'megha'] <class 'numpy.ndarray'> (6,)


In [7]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [10]:
arr5=np.arange(0,11,2)
print(arr5,arr5.shape)

[ 0  2  4  6  8 10] (6,)


In [11]:
arr6=np.linspace(0,100,4)
print(arr6,arr6.shape)

[  0.          33.33333333  66.66666667 100.        ] (4,)


In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [16]:
#operation on arrray

arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened=arr.flatten()
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [19]:
#indexing of array
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

3


In [20]:
#fancy indexing
arr=np.array([1,2,3,4,5])
idx=[0,1,3]
print(arr[idx])

[1 2 4]


In [21]:
#boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>2])

[3 4 5]


In [22]:
#slicing

arr=np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [25]:
#data type
arr=np.array([1,2,3])
arr1=np.array([1,2,3.1,4])
print(arr,arr1,arr.dtype,arr1.dtype)

[1 2 3] [1.  2.  3.1 4. ] int64 float64


In [28]:
#complex
arr1=np.array([3+5j])
arr2=np.array([2+3j])
print(arr1 + arr2)

[5.+8.j]


In [31]:
#multi dimentional array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_column=np.sum(arr2D,axis=0)
print(sum_of_column)

sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [34]:
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

print(arr3D,arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:]) #first row from both layers
print(arr3D[:,:,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
